### ISSUE TITLE
Approval scheme of PR on https://github.com/grincc

### ISSUE THREAD

**Issue by MCM-Mike** [grincc/docs#1]
As all members of the **GRIN community council**  all have owner roles on this repository,  I suggest the following rules for approvals of pull-requests (PR):

**Repository**|  Required members of CC for PR |  notes      
:-----:|:-----:|:-----:|
[agenda](https://github.com/grincc/agenda) | 1 |  CC meeting notes, etc
[security](https://github.com/grincc/security) | 4 | signing, verifying
[finance](https://github.com/grincc/finance) | 4 | public CC fund documentation
[docs](https://github.com/grincc/docs) | 2 | CC related documents 

otherwise anyone of us could approve something without the consent of the other members. 

**CC** = GRIN community council 
**PR** = pull request

**Comment by davidtavarez** [comment]
Makes sense to me.

**Comment by MCM-Mike** [comment]
Can someone please create a `approval-scheme.md` as a PR once we agree on the numbers?
@davidtavarez @marekyggdrasil

**Comment by davidtavarez** [comment]
https://github.com/grincc/docs/pull/3

**Comment by Anynomouss** [comment]
Works for me.

**Comment by MCM-Mike** [comment]
**merged**, will close this issue now.
