### ISSUE TITLE
Useful GRIN links - 

### ISSUE THREAD

**Issue by MCM-Mike** [grincc/docs#4]
**Grin-Basics**
---------------------------------------------------------------------------------------------------
**Website** - https://grin.mw/
**Github** - https://github.com/mimblewimble/grin
**Twitter** - https://twitter.com/grincouncil
**BitcoinTalk Ann** - https://bitcointalk.org/index.php?topic=5090427.0
**Wallet List** - https://github.com/mimblewimble/docs/wiki/Community-projects#wallets
**Grin 'original' wallet user guide** - https://github.com/mimblewimble/docs/wiki/Wallet-User-Guide
**Blockchain explorer** - https://grinscan.net/
**Documentation page** - https://docs.grin.mw/

**Grin-Community:**
---------------------------------------------------------------------------------------------------
**Forum** - https://forum.grin.mw/
**Grin-Privacy** - https://t.me/grinprivacy
**Grin-Traders** - https://t.me/grintrader
**Grin++ Wallet Support** - https://t.me/GrinPP
**Ironbelly Wallet Support** - https://t.me/ironbelly
**NIffler Wallet Support** - https://t.me/nifflerwallet
**Reddit** - https://www.reddit.com/r/grincoin/
**Matrix (new!)** - https://matrix.grincoin.chat/
**Grin marketplace (new!)** - https://slatepacks.com/
**Grin merchandise shop** - https://tmgox.com/

**Grin-Mining Pools:**
---------------------------------------------------------------------------------------------------
http://www.grinmint.com/ *(Terminating on July 21)*
https://goblinpool.com/ *(Too many miners! Switch to another pool!)*
http://pool.always.vip/
https://grin.2miners.com/
https://woolypooly.com/#/coin/grin
https://grin.herominers.com/

**Grin-Resources:**
---------------------------------------------------------------------------------------------------
**Introduction to Grin** - https://github.com/mimblewimble/grin/blob/master/doc/intro.md
**Cuck(at)oo Cycle** - https://github.com/tromp/cuckoo
**What is Grin** - https://phyro.github.io/what-is-grin/mimblewimble.html
**Why Grin** - https://gist.github.com/phyro/ec37d8bfedd36102b0ea5824580d06e4
**Interactive transactions** - https://phyro.github.io/what-is-grin/interactive_txs.html
**Grin's emission schedule** - https://phyro.github.io/what-is-grin/grin_emission.html

**Obsolete:**
---------------------------------------------------------------------------------------------------
**Twitter**: https://twitter.com/grinmw *(Suspended by Twitter)*
**Gitter** -  https://gitter.im/grin_community/Lobby
**Linux miner** - https://github.com/mimblewimble/grin-miner
**Windows miner** - https://github.com/mozkomor/GrinGoldMiner
**Mining pool** - http://mwgrinpool.com/
**Grin 'wallet713' wallet user guide** - https://github.com/vault713/wallet713/blob/master/docs/usage.md
**How to mine Grin with GGM** - https://www.coingecko.com/buzz/how-to-mine-grin?locale=en
**Installing and using the core wallet** - https://www.coingecko.com/buzz/how-to-use-grin-wallet-to-send-receive-grin-coins?locale=en *(HTTP is now deprecated)*
**Installing and Using wallet713** - https://www.coingecko.com/buzz/how-to-use-grin-wallet713-to-send-and-receive-grin-coin-step-by-step-guide?locale=en *(wallet713 is no longer supported)*
**Mining Grin with Bminer** - https://www.coingecko.com/buzz/how-to-mine-grin-coin-with-bminer-step-by-step-guide?locale=en *(Useful resource but some info are outdated)*
**Grincoin FAQ by CoinGecko** - https://www.coingecko.com/buzz/grin-frequently-asked-questions?locale=en *(Useful resource but some info are outdated)*
**Wallet recommendations for newcomers; suggestions welcomed** - https://walletlist.keybase.pub/ *(Useful resource but some info are outdated)*

List was done by `@liqd#3526`  (on GRIN discord) a big thanks :thumbsup: 

Lets also create a PR @davidtavarez and we can let the community add more links or discuss more links.

**Comment by goyle** [comment]
A new category for Grin block explorers

## Grin-Explorers:
https://grinscan.net/ *(Developed by jaspervdm)*
https://grinexplorer.net/ *(Developed by hendi)*
https://grinblocks.online/ *(Developed by bladedoyle)*

*Grin python library, suggested by @bladedoyle*
**Grin python library** - https://github.com/grinfans/grinmw.py

**Comment by marekyggdrasil** [comment]
I would add the following to the `Grin-Resources` section

## Grin-Resources:
**Mimblewimble privacy model was not broken!** - https://medium.com/grin-mimblewimble/factual-inaccuracies-of-breaking-mimblewimbles-privacy-model-8063371839b9

**Comment by goyle** [comment]
*Suggested by @phyro*
> If we ever need to convince people that MW's privacy wasn't broken, here's a comment on Bogaty's article by Pieter Wuille
https://www.reddit.com/r/Bitcoin/comments/e65vdf/could_bitcoins_privacy_benefit_from_litecoins_eb/f9oiuzx/

**Comment by stakervali** [comment]
Is [grinmw twitter](https://twitter.com/grinmw) account still suspended? I can read tweets at the moment.

**Comment by Anynomouss** [comment]
Darn, I somehow overlooked all these great suggestions. I should merge them in:
https://github.com/grincc/hub
I like the format you use @MCM-Mike, much more compact than the current bullet point style I have used. When I or someone else has time, please modify the grin/hub page.

**Comment by Anynomouss** [comment]
All the above suggestions have been incorporated in grin hub https://github.com/grincc/hub
